### ISSUE TITLE
Issue building Popper Bundle

### ISSUE THREAD

**Issue by exinmusic** [aws-solutions/media2cloud#15]
While building the version3 preview locally, popper-bundle build was failing. The archived version being referenced in the package.json still exists, but the directory **popper-core-1.16.0** is not being found. Changing **popper-core-1.16.0** to **floating-ui-1.16.0** in the copy:build line of the package.json for the popper bundle seems to solve the issue.

I will create a PR for your consideration, or if theres a better solution please let me know!
Thanks in advance! (Attached original error below)

```
13 verbose stack Error: popper-bundle@1.16.0 build:copy: `cp -v temp/popper-core-1.16.0/dist/umd/*.min.js ./dist/js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/david/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/david/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid popper-bundle@1.16.0
15 verbose cwd /Users/david/Documents/GitHub/media2cloud/source/webapp/third_party/popper-bundle
16 verbose Darwin 20.6.0
17 verbose argv "/Users/david/.nvm/versions/node/v10.24.1/bin/node" "/Users/david/.nvm/versions/node/v10.24.1/lib/node_modules/npm/bin/npm-cli.js" "run" "build:copy"
18 verbose node v10.24.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error popper-bundle@1.16.0 build:copy: `cp -v temp/popper-core-1.16.0/dist/umd/*.min.js ./dist/js`
22 error Exit status 1
23 error Failed at the popper-bundle@1.16.0 build:copy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by exinmusic** [comment]
Closing, as the above PR solution was merged in. 👍
